stommel:
	gfortran -L/usr/lib -I/usr/include  -I/usr/local/include -L/usr/local/lib -L/usr/lib/lapack -L/usr/lib/libblas -o stommel stommel.f -lnetcdf -lnetcdff -lfftw3  -llapack  -lblas  -fcheck=all -Wall
